CREATE TABLE AGENDAMENTOS (
 ID_AGENDAMENTO NUMBER NOT NULL,
 ID_CONSULTA NUMBER NOT NULL,
 CO_ATEND_PRESTADO VARCHAR2(2) NOT NULL,
 DATA_MARCADA DATE,
 PUSH_ATRASO NUMBER
);

ALTER TABLE AGENDAMENTOS ADD CONSTRAINT PK_AGENDAMENTOS PRIMARY KEY (ID_AGENDAMENTO);


CREATE TABLE ATENDIMENTOS (
 ID_ATENDIMENTO NUMBER NOT NULL,
 ID_SESSAO NUMBER NOT NULL,
 SEQUENCIAL NUMBER(2) NOT NULL,
 CO_ATEND_PRESTADO VARCHAR2(2) NOT NULL,
 ID_MEDICO NUMBER NOT NULL,
 TS_INICIO DATE NOT NULL,
 TS_FIM DATE NOT NULL,
 ID_AGENDAMENTO NUMBER,
 DESCRICAO VARCHAR2(100)
);

ALTER TABLE ATENDIMENTOS ADD CONSTRAINT PK_ATENDIMENTOS PRIMARY KEY (ID_ATENDIMENTO);

CREATE UNIQUE INDEX AK_ATENDIMENTOS ON ATENDIMENTOS (SEQUENCIAL,ID_SESSAO);


CREATE TABLE ATIVIDADES_PROFISSIONAIS (
 COD_CBO VARCHAR2(6) NOT NULL,
 DESCRICAO VARCHAR2(150) NOT NULL,
 TP_CBO_SAUDE CHAR(1)
);

ALTER TABLE ATIVIDADES_PROFISSIONAIS ADD CONSTRAINT PK_ATIVIDADES_PROFISSIONAIS PRIMARY KEY (COD_CBO);


CREATE TABLE CONSULTAS (
 ID_CONSULTA NUMBER NOT NULL
);

ALTER TABLE CONSULTAS ADD CONSTRAINT PK_CONSULTAS PRIMARY KEY (ID_CONSULTA);


CREATE TABLE ESTABELECIMENTOS (
 UNIDADE_ID VARCHAR2(31) NOT NULL,
 CNES VARCHAR2(7),
 LATITUDE NUMBER(3) NOT NULL,
 LONGITUDE NUMBER(3) NOT NULL,
 LOGRADOURO VARCHAR2(60) NOT NULL,
 NUMERO VARCHAR2(10),
 COMPLEMENTO VARCHAR2(60),
 BAIRRO VARCHAR2(60) NOT NULL,
 COD_CEP VARCHAR2(8) NOT NULL,
 TELEFONE VARCHAR2(13),
 FAX VARCHAR2(13),
 EMAIL VARCHAR2(60),
 STATUSMOV CHAR(1)
);

ALTER TABLE ESTABELECIMENTOS ADD CONSTRAINT PK_ESTABELECIMENTOS PRIMARY KEY (UNIDADE_ID);


CREATE TABLE ESTADOS (
 UF VARCHAR2(2) NOT NULL,
 NOME VARCHAR2(20) NOT NULL
);

ALTER TABLE ESTADOS ADD CONSTRAINT PK_ESTADOS PRIMARY KEY (UF);


CREATE TABLE EXAMES (
 ID_EXAME NUMBER NOT NULL
);

ALTER TABLE EXAMES ADD CONSTRAINT PK_EXAMES PRIMARY KEY (ID_EXAME);


CREATE TABLE METODOS_LOCALIZACAO (
 ID_METODO CHAR(1) NOT NULL,
 DESCRICAO VARCHAR2(20)
);

ALTER TABLE METODOS_LOCALIZACAO ADD CONSTRAINT PK_METODOS_LOCALIZACAO PRIMARY KEY (ID_METODO);


CREATE TABLE MUNICIPIOS (
 COD_MUN VARCHAR2(6) NOT NULL,
 NOME_MUN VARCHAR2(60) NOT NULL,
 UF VARCHAR2(2) NOT NULL
);

ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_MUNICIPIOS PRIMARY KEY (COD_MUN);

CREATE UNIQUE INDEX AK_MUNICIPIOS ON MUNICIPIOS (UF,NOME_MUN);


CREATE TABLE OPCOES (
 ID_OPCAO NUMBER NOT NULL,
 VALOR VARCHAR2(30) NOT NULL
);

ALTER TABLE OPCOES ADD CONSTRAINT PK_OPCOES PRIMARY KEY (ID_OPCAO);


CREATE TABLE PERGUNTAS (
 ID_PERGUNTA NUMBER NOT NULL,
 ENUNCIADO VARCHAR2(60) NOT NULL,
 TIPO CHAR(1) NOT NULL,
 MAX_OPCOES NUMBER
);

ALTER TABLE PERGUNTAS ADD CONSTRAINT PK_PERGUNTAS PRIMARY KEY (ID_PERGUNTA);


CREATE TABLE PROCEDIMENTOS (
 ID_PROCEDIMENTO NUMBER NOT NULL
);

ALTER TABLE PROCEDIMENTOS ADD CONSTRAINT PK_PROCEDIMENTOS PRIMARY KEY (ID_PROCEDIMENTO);


CREATE TABLE TIPOS_DE_ATENDIMENTO (
 CO_ATEND_PRESTADO VARCHAR2(2) NOT NULL,
 DESCRICAO VARCHAR2(60),
 CATEGORIA CHAR(1)
);

ALTER TABLE TIPOS_DE_ATENDIMENTO ADD CONSTRAINT PK_TIPOS_DE_ATENDIMENTO PRIMARY KEY (CO_ATEND_PRESTADO);


CREATE TABLE USUARIOS (
 ID_USUARIO NUMBER NOT NULL,
 NUM_TELEFONE NUMBER(15) NOT NULL,
 TS_CADASTRO DATE
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO);

CREATE UNIQUE INDEX AK_USUARIOS ON USUARIOS (NUM_TELEFONE);


CREATE TABLE END_COMPL_ESTAB (
 UNIDADE_ID VARCHAR2(31) NOT NULL,
 LOGRADOURO VARCHAR2(60) NOT NULL,
 NUMERO VARCHAR2(10),
 COMPLEMENTO VARCHAR2(60),
 BAIRRO VARCHAR2(60),
 COD_CEP VARCHAR2(8) NOT NULL,
 DDD_TEL VARCHAR2(3),
 TELEFONE VARCHAR2(40),
 DDD_FAX VARCHAR2(3),
 FAX VARCHAR2(40),
 EMAIL VARCHAR2(60),
 COD_MUN VARCHAR2(6) NOT NULL
);

ALTER TABLE END_COMPL_ESTAB ADD CONSTRAINT PK_END_COMPL_ESTAB PRIMARY KEY (UNIDADE_ID);


CREATE TABLE ESTAB_HORARIOS_ATEND (
 ESTAB_HORARIO_ATEND_ID VARCHAR2(16) NOT NULL,
 UNIDADE_ID VARCHAR2(31) NOT NULL,
 CO_DIA_SEMANA NUMBER(2) NOT NULL,
 HR_INICIO_ATENDIMENTO VARCHAR2(5) NOT NULL,
 HR_FIM_ATENDIMENTO VARCHAR2(5) NOT NULL
);

ALTER TABLE ESTAB_HORARIOS_ATEND ADD CONSTRAINT PK_ESTAB_HORARIOS_ATEND PRIMARY KEY (ESTAB_HORARIO_ATEND_ID);

CREATE UNIQUE INDEX AK_ESTAB_HORA_ATEND_UNIDADE_ID ON ESTAB_HORARIOS_ATEND (CO_DIA_SEMANA,HR_INICIO_ATENDIMENTO,UNIDADE_ID);


CREATE TABLE OPCOES_PERGUNTAS (
 ID_OPCAO_PERGUNTA NUMBER NOT NULL,
 ID_PERGUNTA NUMBER NOT NULL,
 ID_OPCAO NUMBER NOT NULL
);

ALTER TABLE OPCOES_PERGUNTAS ADD CONSTRAINT PK_OPCOES_PERGUNTAS PRIMARY KEY (ID_OPCAO_PERGUNTA);

CREATE UNIQUE INDEX AK_OPCOES_PERGUNTAS ON OPCOES_PERGUNTAS (ID_PERGUNTA,ID_OPCAO);


CREATE TABLE PACIENTES (
 ID_PACIENTE NUMBER NOT NULL
);

ALTER TABLE PACIENTES ADD CONSTRAINT PK_PACIENTES PRIMARY KEY (ID_PACIENTE);


CREATE TABLE PROFISSIONAIS (
 ID_USUARIO NUMBER NOT NULL,
 PROF_ID VARCHAR2(16) NOT NULL,
 CPF_PROF VARCHAR2(11) NOT NULL,
 NOME_PROF VARCHAR2(60) NOT NULL,
 DATA_NASC DATE,
 SEXO CHAR(1),
 STATUSMOV CHAR(1),
 NO_EMAIL VARCHAR2(60)
);

ALTER TABLE PROFISSIONAIS ADD CONSTRAINT PK_PROFISSIONAIS PRIMARY KEY (ID_USUARIO);

CREATE UNIQUE INDEX AK_PROFISSIONAIS ON PROFISSIONAIS (PROF_ID);


CREATE TABLE SEQUENCIAS_PERGUNTAS (
 ID_SEQUENCIA_PERGUNTA NUMBER NOT NULL,
 ID_PERGUNTA NUMBER NOT NULL,
 ID_PROX_PERGUNTA NUMBER NOT NULL,
 ID_OPCAO_ESCOLHIDA NUMBER NOT NULL
);

ALTER TABLE SEQUENCIAS_PERGUNTAS ADD CONSTRAINT PK_SEQUENCIAS_PERGUNTAS PRIMARY KEY (ID_SEQUENCIA_PERGUNTA);

CREATE UNIQUE INDEX AK_SEQUENCIAS_PERGUNTAS ON SEQUENCIAS_PERGUNTAS (ID_PROX_PERGUNTA,ID_PERGUNTA);


CREATE TABLE SESSOES (
 ID_SESSAO NUMBER NOT NULL,
 ID_PACIENTE NUMBER NOT NULL,
 UNIDADE_ID VARCHAR2(31) NOT NULL,
 CHECK_IN DATE NOT NULL,
 CK_IN_MET_UTILIZADO CHAR(1) NOT NULL,
 CK_IN_PUSH_ATRASO NUMBER,
 CHECK_OUT DATE NOT NULL,
 CK_OUT_MET_UTILIZADO CHAR(1) NOT NULL,
 CK_OUT_GEO_COORD_LAT NUMBER,
 CK_OUT_GEO_COORD_LONG NUMBER,
 CK_OUT_PUSH_ATRASO NUMBER,
 DISP_MOV_MODELO VARCHAR2(20),
 DISP_MOV_MARCA VARCHAR2(20),
 DISP_MOV_SISOP VARCHAR2(20)
);

ALTER TABLE SESSOES ADD CONSTRAINT PK_SESSOES PRIMARY KEY (ID_SESSAO);


CREATE TABLE TIPOS_ATEND_ESTAB (
 ID_TIPOS_ATEND_ESTAB NUMBER NOT NULL,
 UNIDADE_ID VARCHAR2(31) NOT NULL,
 CO_ATEND_PRESTADO VARCHAR2(2) NOT NULL
);

ALTER TABLE TIPOS_ATEND_ESTAB ADD CONSTRAINT PK_TIPOS_ATEND_ESTAB PRIMARY KEY (ID_TIPOS_ATEND_ESTAB);

CREATE UNIQUE INDEX AK_TIPOS_ATEND_ESTAB ON TIPOS_ATEND_ESTAB (CO_ATEND_PRESTADO,UNIDADE_ID);


CREATE TABLE ENDERECOS (
 ID_ENDERECO NUMBER NOT NULL,
 ID_PACIENTE NUMBER NOT NULL,
 TS_CADASTRO DATE,
 LOGRADOURO VARCHAR2(60),
 NUMERO VARCHAR2(10),
 COMPLEMENTO VARCHAR2(60),
 BAIRRO VARCHAR2(60),
 COD_CEP VARCHAR2(8)
);

ALTER TABLE ENDERECOS ADD CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID_ENDERECO);


CREATE TABLE MEDICOS (
 ID_MEDICO NUMBER NOT NULL
);

ALTER TABLE MEDICOS ADD CONSTRAINT PK_MEDICOS PRIMARY KEY (ID_MEDICO);


CREATE TABLE PROCURAS (
 ID_PROCURA NUMBER NOT NULL,
 ID_PACIENTE NUMBER NOT NULL,
 TS_PROCURA DATE,
 ID_METODO CHAR(1) NOT NULL,
 ID_ENDERECO NUMBER,
 GEO_COORD_LAT NUMBER,
 GEO_COORD_LONG NUMBER
);

ALTER TABLE PROCURAS ADD CONSTRAINT PK_PROCURAS PRIMARY KEY (ID_PROCURA);


CREATE TABLE PROF_ESTAB (
 ID_PROF_ESTAB NUMBER NOT NULL,
 UNIDADE_ID VARCHAR2(31) NOT NULL,
 ID_USUARIO NUMBER NOT NULL,
 COD_CBO VARCHAR2(6) NOT NULL
);

ALTER TABLE PROF_ESTAB ADD CONSTRAINT PK_PROF_ESTAB PRIMARY KEY (ID_PROF_ESTAB);

CREATE UNIQUE INDEX AK_PROF_ESTAB ON PROF_ESTAB (UNIDADE_ID,ID_USUARIO);


CREATE TABLE RESPOSTAS_PERGUNTAS (
 ID_RESPOSTA_PERGUNTA NUMBER NOT NULL,
 ID_SESSAO NUMBER NOT NULL,
 ID_PERGUNTA NUMBER NOT NULL,
 ID_OPCAO NUMBER,
 TEXTO_RESPOSTA VARCHAR2(300)
);

ALTER TABLE RESPOSTAS_PERGUNTAS ADD CONSTRAINT PK_RESPOSTAS_PERGUNTAS PRIMARY KEY (ID_RESPOSTA_PERGUNTA);


ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_0 FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTAS (ID_CONSULTA);
ALTER TABLE AGENDAMENTOS ADD CONSTRAINT FK_AGENDAMENTOS_1 FOREIGN KEY (CO_ATEND_PRESTADO) REFERENCES TIPOS_DE_ATENDIMENTO (CO_ATEND_PRESTADO);


ALTER TABLE ATENDIMENTOS ADD CONSTRAINT FK_ATENDIMENTOS_0 FOREIGN KEY (ID_SESSAO) REFERENCES SESSOES (ID_SESSAO);
ALTER TABLE ATENDIMENTOS ADD CONSTRAINT FK_ATENDIMENTOS_1 FOREIGN KEY (CO_ATEND_PRESTADO) REFERENCES TIPOS_DE_ATENDIMENTO (CO_ATEND_PRESTADO);
ALTER TABLE ATENDIMENTOS ADD CONSTRAINT FK_ATENDIMENTOS_2 FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS (ID_MEDICO);
ALTER TABLE ATENDIMENTOS ADD CONSTRAINT FK_ATENDIMENTOS_3 FOREIGN KEY (ID_AGENDAMENTO) REFERENCES AGENDAMENTOS (ID_AGENDAMENTO);


ALTER TABLE CONSULTAS ADD CONSTRAINT FK_CONSULTAS_0 FOREIGN KEY (ID_CONSULTA) REFERENCES ATENDIMENTOS (ID_ATENDIMENTO);


ALTER TABLE EXAMES ADD CONSTRAINT FK_EXAMES_0 FOREIGN KEY (ID_EXAME) REFERENCES ATENDIMENTOS (ID_ATENDIMENTO);


ALTER TABLE MUNICIPIOS ADD CONSTRAINT FK_MUNICIPIOS_0 FOREIGN KEY (UF) REFERENCES ESTADOS (UF);


ALTER TABLE PROCEDIMENTOS ADD CONSTRAINT FK_PROCEDIMENTOS_0 FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES ATENDIMENTOS (ID_ATENDIMENTO);


ALTER TABLE END_COMPL_ESTAB ADD CONSTRAINT FK_END_COMPL_ESTAB_0 FOREIGN KEY (UNIDADE_ID) REFERENCES ESTABELECIMENTOS (UNIDADE_ID);
ALTER TABLE END_COMPL_ESTAB ADD CONSTRAINT FK_END_COMPL_ESTAB_1 FOREIGN KEY (COD_MUN) REFERENCES MUNICIPIOS (COD_MUN);


ALTER TABLE ESTAB_HORARIOS_ATEND ADD CONSTRAINT FK_ESTAB_HORARIOS_ATEND_0 FOREIGN KEY (UNIDADE_ID) REFERENCES ESTABELECIMENTOS (UNIDADE_ID);


ALTER TABLE OPCOES_PERGUNTAS ADD CONSTRAINT FK_OPCOES_PERGUNTAS_0 FOREIGN KEY (ID_PERGUNTA) REFERENCES PERGUNTAS (ID_PERGUNTA);
ALTER TABLE OPCOES_PERGUNTAS ADD CONSTRAINT FK_OPCOES_PERGUNTAS_1 FOREIGN KEY (ID_OPCAO) REFERENCES OPCOES (ID_OPCAO);


ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_0 FOREIGN KEY (ID_PACIENTE) REFERENCES USUARIOS (ID_USUARIO);


ALTER TABLE PROFISSIONAIS ADD CONSTRAINT FK_PROFISSIONAIS_0 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO);


ALTER TABLE SEQUENCIAS_PERGUNTAS ADD CONSTRAINT FK_SEQUENCIAS_PERGUNTAS_0 FOREIGN KEY (ID_PERGUNTA) REFERENCES PERGUNTAS (ID_PERGUNTA);
ALTER TABLE SEQUENCIAS_PERGUNTAS ADD CONSTRAINT FK_SEQUENCIAS_PERGUNTAS_1 FOREIGN KEY (ID_PROX_PERGUNTA) REFERENCES PERGUNTAS (ID_PERGUNTA);
ALTER TABLE SEQUENCIAS_PERGUNTAS ADD CONSTRAINT FK_SEQUENCIAS_PERGUNTAS_2 FOREIGN KEY (ID_OPCAO_ESCOLHIDA) REFERENCES OPCOES_PERGUNTAS (ID_OPCAO_PERGUNTA);


ALTER TABLE SESSOES ADD CONSTRAINT FK_SESSOES_0 FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID_PACIENTE);
ALTER TABLE SESSOES ADD CONSTRAINT FK_SESSOES_1 FOREIGN KEY (UNIDADE_ID) REFERENCES ESTABELECIMENTOS (UNIDADE_ID);
ALTER TABLE SESSOES ADD CONSTRAINT FK_SESSOES_2 FOREIGN KEY (CK_OUT_MET_UTILIZADO) REFERENCES METODOS_LOCALIZACAO (ID_METODO);


ALTER TABLE TIPOS_ATEND_ESTAB ADD CONSTRAINT FK_TIPOS_ATEND_ESTAB_0 FOREIGN KEY (UNIDADE_ID) REFERENCES ESTABELECIMENTOS (UNIDADE_ID);
ALTER TABLE TIPOS_ATEND_ESTAB ADD CONSTRAINT FK_TIPOS_ATEND_ESTAB_1 FOREIGN KEY (CO_ATEND_PRESTADO) REFERENCES TIPOS_DE_ATENDIMENTO (CO_ATEND_PRESTADO);


ALTER TABLE ENDERECOS ADD CONSTRAINT FK_ENDERECOS_0 FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID_PACIENTE);


ALTER TABLE MEDICOS ADD CONSTRAINT FK_MEDICOS_0 FOREIGN KEY (ID_MEDICO) REFERENCES PROFISSIONAIS (ID_USUARIO);


ALTER TABLE PROCURAS ADD CONSTRAINT FK_PROCURAS_0 FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID_PACIENTE);
ALTER TABLE PROCURAS ADD CONSTRAINT FK_PROCURAS_1 FOREIGN KEY (ID_METODO) REFERENCES METODOS_LOCALIZACAO (ID_METODO);
ALTER TABLE PROCURAS ADD CONSTRAINT FK_PROCURAS_2 FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS (ID_ENDERECO);


ALTER TABLE PROF_ESTAB ADD CONSTRAINT FK_PROF_ESTAB_0 FOREIGN KEY (UNIDADE_ID) REFERENCES ESTABELECIMENTOS (UNIDADE_ID);
ALTER TABLE PROF_ESTAB ADD CONSTRAINT FK_PROF_ESTAB_1 FOREIGN KEY (ID_USUARIO) REFERENCES PROFISSIONAIS (ID_USUARIO);
ALTER TABLE PROF_ESTAB ADD CONSTRAINT FK_PROF_ESTAB_2 FOREIGN KEY (COD_CBO) REFERENCES ATIVIDADES_PROFISSIONAIS (COD_CBO);


ALTER TABLE RESPOSTAS_PERGUNTAS ADD CONSTRAINT FK_RESPOSTAS_PERGUNTAS_0 FOREIGN KEY (ID_SESSAO) REFERENCES SESSOES (ID_SESSAO);
ALTER TABLE RESPOSTAS_PERGUNTAS ADD CONSTRAINT FK_RESPOSTAS_PERGUNTAS_1 FOREIGN KEY (ID_PERGUNTA) REFERENCES PERGUNTAS (ID_PERGUNTA);
ALTER TABLE RESPOSTAS_PERGUNTAS ADD CONSTRAINT FK_RESPOSTAS_PERGUNTAS_2 FOREIGN KEY (ID_PERGUNTA,ID_OPCAO) REFERENCES OPCOES_PERGUNTAS (ID_PERGUNTA,ID_OPCAO);


